---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: Composition
metadata:
  name: gcp-cluster
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  reclaimPolicy: Delete
  from:
    apiVersion: common.crossplane.io/v1alpha1
    kind: KubernetesCluster
  to:
    - base:
        apiVersion: container.gcp.crossplane.io/v1beta1
        kind: GKECluster
        spec:
          forProvider:
            initialClusterVersion: "1.15"
            location: $(REGION)-b
            masterAuth:
              username: admin
            ipAllocationPolicy:
              useIpAliases: true
              clusterSecondaryRangeName: pods
              servicesSecondaryRangeName: services
            subnetworkSelector:
              matchControllerRef: true
            networkSelector:
              matchLabels:
                crossplane.io/composite: network
          writeConnectionSecretToRef:
            namespace: crossplane-system
          providerRef:
            name: gcp-provider
      patches:
        - fromFieldPath: "metadata.labels"
          toFieldPath: "metadata.labels"
        - fromFieldPath: "metadata.annotations[crossplane.io/external-name]"
          toFieldPath: "metadata.annotations[crossplane.io/external-name]"
        - fromFieldPath: "spec.reclaimPolicy"
          toFieldPath: "spec.reclaimPolicy"
        - fromFieldPath: "spec.version"
          toFieldPath: "spec.forProvider.initialClusterVersion"
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-kubecfg"
      connectionDetails:
        - fromConnectionSecretKey: kubeconfig
    - base:
        apiVersion: container.gcp.crossplane.io/v1alpha1
        kind: NodePool
        spec:
          forProvider:
            locations:
              - $(REGION)-b
            initialNodeCount: 1
            config:
              machineType: n1-standard-1
            clusterSelector:
              matchControllerRef: true
          providerRef:
            name: gcp-provider
      patches:
        - fromFieldPath: "metadata.labels"
          toFieldPath: "metadata.labels"
        - fromFieldPath: "spec.reclaimPolicy"
          toFieldPath: "spec.reclaimPolicy"
    - base:
        apiVersion: compute.gcp.crossplane.io/v1beta1
        kind: Subnetwork
        spec:
          forProvider:
            region: $(REGION)
            ipCidrRange: "192.168.0.0/24"
            privateIpGoogleAccess: true
            secondaryIpRanges:
              - rangeName: pods
                ipCidrRange: 10.128.0.0/20
              - rangeName: services
                ipCidrRange: 172.16.0.0/16
            networkSelector:
              matchLabels:
                crossplane.io/composite: network
          providerRef:
            name: gcp-provider
      patches:
        - fromFieldPath: "metadata.labels"
          toFieldPath: "metadata.labels"
        - fromFieldPath: "spec.reclaimPolicy"
          toFieldPath: "spec.reclaimPolicy"