# This file is used to define a custom transformers for our CRDs so that Kustomize
# can resolve the cross-resource object references.
# See https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/crd/README.md

# nameReference is used to declare which kind's name is referred in which resources.
nameReference:
  - kind: PrivateNetwork
    fieldSpecs:
      - path: spec/to/base/spec/forProvider/networkSelector/matchLabels/crossplane.io\/composite
        kind: Composition
      - path: spec/to/base/spec/forProvider/networkSelector/matchLabels/crossplane.io\/composite
        kind: Composition
  - kind: Provider
    fieldSpecs:
      - path: spec/to/base/spec/providerRef
        kind: Composition


# varReference is the list of fields that we tell Kustomize to process for
# variants.
varReference:
  - path: spec/to/base/spec/forProvider/location
    kind: Composition
  - path: spec/to/base/spec/forProvider/locations
    kind: Composition
  - path: spec/to/base/spec/forProvider/region
    kind: Composition