# This file is used to define a custom transformers for our CRDs so that Kustomize
# can resolve the cross-resource object references.
# See https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/crd/README.md

# nameReference is used to declare which kind's name is referred in which resources.
nameReference:
  - kind: Network
    fieldSpecs:
      - path: spec/forProvider/networkRef/name
        kind: Subnetwork
      - path: spec/forProvider/networkRef/name
        kind: GlobalAddress
      - path: spec/to/base/spec/forProvider/networkRef/name
        kind: Composition
  - kind: Subnetwork
    fieldSpecs:
      - path: spec/to/base/spec/forProvider/subnetworkRef/name
        kind: Composition
  - kind: Provider
    fieldSpecs:
      - path: spec/providerRef/name
        kind: Network
      - path: spec/providerRef/name
        kind: Subnetwork
      - path: spec/providerRef/name
        kind: GlobalAddress
      - path: spec/to/base/spec/providerRef
        kind: Composition


# varReference is the list of fields that we tell Kustomize to process for
# variants.
varReference:
  - path: spec/to/base/spec/forProvider/location
    kind: Composition
  - path: spec/to/base/spec/forProvider/locations
    kind: Composition
  - path: spec/forProvider/region
    kind: Subnetwork