title: "GCP Sample Stack"
overviewShort: |
  Configures a GCP environment with basic networking, security,
  and default resource classes for applications to use.
overview: |
  Configures a GCP environment with basic networking, security,
  and default resource classes that provide a self-service catalog
  for applications to use.
readme: |
  The `GCP Sample Stack` configures the neccesary cloud resources and
  self-service catalog to deploy basic applications like `Wordpress`.

  The managed resources configured by this stack include:
  `Network`, `Subnetwork`, `GlobalAddress`, and `Connection`.

  This stack offers the following resource classes for applications to
  use: `GKEClusterClass`, `CloudSQLInstanceClass`, and
  `CloudMemorystoreInstanceClass`.

  The `GCP Sample Stack` also configures a `Provider` connection resource,
  so the `GCP Provider` can communicate with GCP API.

  [Learn More on GitHub](https://github.com/crossplane/stack-gcp-sample)
  to see the complete `kustomize` templates used in this stack and
  as a starting point for building your own stack.
maintainers:
  - name: "Muvaffak Onus"
    email: "monus@upbound.io"
owners:
  - name: "Muvaffak Onus"
    email: "monus@upbound.io"
company: "Crossplane"
category: "Sample Stack"
packageType: "Stack"
keywords:
  - "easy"
  - "resource class"
  - "private network"
  - "sample"
website: "https://crossplane.io"
source: "https://github.com/crossplane/stack-gcp-sample"
permissionScope: Cluster
dependsOn:
  - crd: '*.cache.gcp.crossplane.io/v1beta1'
  - crd: '*.compute.gcp.crossplane.io/v1alpha3'
  - crd: '*.database.gcp.crossplane.io/v1beta1'
  - crd: '*.storage.gcp.crossplane.io/v1alpha3'
  - crd: '*.servicenetworking.gcp.crossplane.io/v1alpha3'
  - crd: '*.gcp.crossplane.io/v1alpha3'
  - package: 'crossplane/provider-gcp'
# License SPDX name: https://spdx.org/licenses/
license: Apache-2.0
